-- Employee Movement Management
-- Additive migration for MySQL 8.0+. The application initializer dynamically matches employees.id.
-- This migration uses the current HRIS employee ID collation.

CREATE TABLE IF NOT EXISTS personnel_movements (
    id CHAR(36) NOT NULL PRIMARY KEY,
    control_number VARCHAR(80) NOT NULL,
    employee_id CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    action_type VARCHAR(60) NOT NULL,
    status ENUM('Draft','Submitted','Reviewed','Approved','Posted','Rejected','Reversed') NOT NULL DEFAULT 'Draft',
    effective_date DATE NOT NULL,
    end_date DATE NULL,
    authority_number VARCHAR(160) NULL,
    authority_date DATE NULL,
    target_plantilla_item_id CHAR(36) NULL,
    target_position_id INT UNSIGNED NULL,
    target_salary_grade_id INT UNSIGNED NULL,
    target_department VARCHAR(200) NULL,
    remarks TEXT NULL,
    supporting_documents JSON NULL,
    source_snapshot_json JSON NOT NULL,
    posted_before_snapshot_json JSON NULL,
    posted_after_snapshot_json JSON NULL,
    prepared_by INT UNSIGNED NULL,
    submitted_by INT UNSIGNED NULL,
    reviewed_by INT UNSIGNED NULL,
    approved_by INT UNSIGNED NULL,
    posted_by INT UNSIGNED NULL,
    rejected_by INT UNSIGNED NULL,
    reversed_by INT UNSIGNED NULL,
    submitted_at DATETIME NULL,
    reviewed_at DATETIME NULL,
    approved_at DATETIME NULL,
    posted_at DATETIME NULL,
    rejected_at DATETIME NULL,
    reversed_at DATETIME NULL,
    decision_remarks TEXT NULL,
    reversal_reason TEXT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_personnel_movement_control (control_number),
    INDEX idx_movement_employee_date (employee_id,effective_date),
    INDEX idx_movement_status_date (status,effective_date),
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE RESTRICT,
    FOREIGN KEY (target_plantilla_item_id) REFERENCES plantilla_items(id) ON DELETE RESTRICT,
    FOREIGN KEY (target_position_id) REFERENCES positions(id) ON DELETE RESTRICT,
    FOREIGN KEY (target_salary_grade_id) REFERENCES salary_grades(id) ON DELETE RESTRICT,
    FOREIGN KEY (prepared_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (submitted_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (posted_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (rejected_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (reversed_by) REFERENCES users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB; 
CREATE TABLE IF NOT EXISTS personnel_movement_events (
    id CHAR(36) NOT NULL PRIMARY KEY,
    movement_id CHAR(36) NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    from_status VARCHAR(20) NULL,
    to_status VARCHAR(20) NOT NULL,
    actor_id INT UNSIGNED NULL,
    remarks TEXT NULL,
    snapshot_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_movement_events (movement_id,created_at),
    FOREIGN KEY (movement_id) REFERENCES personnel_movements(id) ON DELETE RESTRICT,
    FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB; 
